
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://effaassdrpabvpgoulrq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVmZmFhc3NkcnBhYnZwZ291bHJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMzIxOTAsImV4cCI6MjA1OTcwODE5MH0.RJGPOubUVdLfWOHdEFVPPxrGk90eO7lBoxywHFaV2KU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Helper function to check if user has a specific permission
export const checkPermission = async (permissionId: string): Promise<boolean> => {
  try {
    const { data: { session } } = await supabase.auth.getSession();
    
    if (!session) return false;
    
    const { data, error } = await supabase
      .from('user_permissions')
      .select('*')
      .eq('user_id', session.user.id)
      .eq('permission_id', permissionId)
      .single();
    
    if (error) {
      console.error('Permission check error:', error);
      return false;
    }
    
    return !!data;
  } catch (error) {
    console.error('Permission check error:', error);
    return false;
  }
};

// Helper function to get current user profile
export const getCurrentUserProfile = async () => {
  try {
    const { data: { session } } = await supabase.auth.getSession();
    
    if (!session) return null;
    
    const { data, error } = await supabase
      .from('profiles')
      .select('*')
      .eq('id', session.user.id)
      .single();
    
    if (error) {
      console.error('Get profile error:', error);
      return null;
    }
    
    return data;
  } catch (error) {
    console.error('Get profile error:', error);
    return null;
  }
};
